[package]
name = "rolf"
version = "0.1.0"
authors = ["Christopher Chang <chiggiechang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20" # Cross-platform terminal drawing
open = "1.7.0" # Cross-platform file opener
which = "4.1.0" # Cross-platform equivalent of Unix 'which'
