[package]
name = "cranger"
version = "0.1.0"
authors = ["Christopher Chang <chiggiechang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20"
open = "1.7.0"
