name: macOS build

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-11

    env:
      # Used for codesigning executable
      MACOS_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_BASE64 }}
      MACOS_CERTIFICATE_PWD: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      # Used for notarizing artifact
      AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
      AC_USERNAME: ${{ secrets.AC_USERNAME }}

      ARM_EXEC_PATH: target/aarch64-apple-darwin/release/rolf
      ARM_RELEASE_DIR: rolf-macos-arm
      ARM_ARTIFACT_ZIP: rolf-macos-arm.zip

      AMD_EXEC_PATH: target/x86_64-apple-darwin/release/rolf
      AMD_RELEASE_DIR: rolf-macos
      AMD_ARTIFACT_ZIP: rolf-macos.zip

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v1
        
      - name: Install Rust (ARM)
        run: |
          rustup target add aarch64-apple-darwin
      
      - name: Make a macOS 11 ARM build
        run: |
          cargo build --target aarch64-apple-darwin --release --locked
          ls target/**

      - name: Make a macOS 11 Intel build
        run: |
          cargo build --target x86_64-apple-darwin --all --release
          ls target/**

      # https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions
      # https://artyom.dev/notarizing-go-binaries-for-macos.html
      # https://www.andrewhoefling.com/Blog/Post/how-to-develop-ios-without-a-mac
      - name: Codesign/notarize executable and artifact for ARM
        run: |
          ci/sign_notarize_artifact "$ARM_EXEC_PATH" "$ARM_RELEASE_DIR" "$ARM_ARTIFACT_ZIP"

      - name: Codesign/notarize executable and artifact for Intel
        run: |
          ci/sign_notarize_artifact "$AMD_EXEC_PATH" "$AMD_RELEASE_DIR" "$AMD_ARTIFACT_ZIP"
      
      - uses: actions/upload-artifact@v3
        with:
          name: macos-build-arm
          path: ${{ env.ARM_ARTIFACT_ZIP }}

      - uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: ${{ env.AMD_ARTIFACT_ZIP }}

      - name: Delete old tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: macos-latest # tag name to delete
          # repo: <owner>/<repoName> # target repo (optional). defaults to repo running this action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "NAME_WITH_SHA=macOS Pre-release $GITHUB_SHA" >> $GITHUB_ENV
      
      - name: Make pre-release
        # uses: softprops/action-gh-release@v1
        uses: softprops/action-gh-release@59c3b4891632ff9a897f99a91d7bc557467a3a22
        with:
          files: |
            ${{ env.ARM_ARTIFACT_ZIP }}
            ${{ env.AMD_ARTIFACT_ZIP }}
          name: ${{ env.NAME_WITH_SHA }}
          prerelease: true
          tag_name: macos-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
