# This workflow just makes a macOS build. It doesn't (yet) make this build distributable.
# We may be able to use https://github.com/wez/wezterm/actions/runs/1911320345/workflow
# and https://github.com/wez/wezterm/blob/main/ci/deploy.sh as references.

name: macOS build (non-distributable)

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v1
      
      - name: Make a macOS 11 build
        run: cargo build --release --locked
